services:
  nginx:
    image: nginx:alpine
    container_name: bayliq-api-nginx
    working_dir: /var/www/bayliq-api
    volumes:
      - ./:/var/www/bayliq-api
      - ./docker/nginx/bayliq-local.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - postgres
    depends_on:
      - php
      - postgres
    ports:
      - 8063:80

  redis:
    container_name: bayliq-api-redis
    build: ./docker/redis
    volumes:
      - redis_bayliq-api:/data
    ports:
      - "6363:6379"

  php:
    container_name: bayliq-api-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/bayliq-api
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/z-php.ini
    working_dir: /var/www/bayliq-api
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    ports:
      - 9063:9000

  postgres:
    container_name: bayliq-api-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: bayliq_db
      POSTGRES_USER: bayliq_user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres_bayliq-api:/data/postgres
    ports:
      - 5463:5432

volumes:
  postgres_bayliq-api:
    driver: local
  redis_bayliq-api:
    driver: local
