name: 🚀 Deploy Laravel App to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🔄 Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: 🚀 Deploy via SSH
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.PROJECT_DIR }}
            git pull origin main
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
            docker exec -i bayliq-api-php bash -c "composer install --no-dev --optimize-autoloader"
            docker exec -i bayliq-api-php php artisan migrate --force
            docker exec -i bayliq-api-php php artisan config:cache
            docker exec -i bayliq-api-php php artisan route:cache
            docker exec -i bayliq-api-php php artisan view:cache
          EOF
